{% set version = "1.3.9" %}

package:
  name: scatterd
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/scatterd/scatterd-{{ version }}.tar.gz
  sha256: 7a7b94d946c8a16b6ece756a4a80210a6fe9bc0e4d51c41aae6426fd865e7841

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - colourmap >=1.1.16
    - seaborn
    - datazets

test:
  commands:
    - pip check
  imports:
    - scatterd
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://erdogant.github.io/scatterd
  summary: scatterd is an easy and fast way of creating scatter plots.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
